// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.nym_transport;

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicBoolean
import java.util.concurrent.atomic.AtomicLong

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    @JvmField var capacity: Int = 0
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

    companion object {
        internal fun alloc(size: Int = 0) = rustCall() { status ->
            _UniFFILib.INSTANCE.ffi_uniffi_nym_transport_rustbuffer_alloc(size, status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: Int, len: Int, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity
            buf.len = len
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = rustCall() { status ->
            _UniFFILib.INSTANCE.ffi_uniffi_nym_transport_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

/**
 * The equivalent of the `*mut RustBuffer` type.
 * Required for callbacks taking in an out pointer.
 *
 * Size is the sum of all values in the struct.
 */
class RustBufferByReference : ByReference(16) {
    /**
     * Set the pointed-to `RustBuffer` to the given value.
     */
    fun setValue(value: RustBuffer.ByValue) {
        // NOTE: The offsets are as they are in the C-like struct.
        val pointer = getPointer()
        pointer.setInt(0, value.capacity)
        pointer.setInt(4, value.len)
        pointer.setPointer(8, value.data)
    }

    /**
     * Get a `RustBuffer.ByValue` from this reference.
     */
    fun getValue(): RustBuffer.ByValue {
        val pointer = getPointer()
        val value = RustBuffer.ByValue()
        value.writeField("capacity", pointer.getInt(0))
        value.writeField("len", pointer.getInt(4))
        value.writeField("data", pointer.getPointer(8))

        return value
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
// The FfiConverter interface handles converter types to and from the FFI
//
// All implementing objects should be public to support external types.  When a
// type is external we need to import it's FfiConverter.
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): Int

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity.toLong()).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

// FfiConverter that uses `RustBuffer` as the FfiType
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.
// Error runtime.
@Structure.FieldOrder("code", "error_buf")
internal open class RustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: RustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == 0.toByte()
    }

    fun isError(): Boolean {
        return code == 1.toByte()
    }

    fun isPanic(): Boolean {
        return code == 2.toByte()
    }
}

class InternalException(message: String) : Exception(message)

// Each top-level error class has a companion object that can lift the error from the call status's rust buffer
interface CallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: Exception> rustCallWithError(errorHandler: CallStatusErrorHandler<E>, callback: (RustCallStatus) -> U): U {
    var status = RustCallStatus();
    val return_value = callback(status)
    checkCallStatus(errorHandler, status)
    return return_value
}

// Check RustCallStatus and throw an error if the call wasn't successful
private fun<E: Exception> checkCallStatus(errorHandler: CallStatusErrorHandler<E>, status: RustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

// CallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
object NullCallStatusErrorHandler: CallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> rustCall(callback: (RustCallStatus) -> U): U {
    return rustCallWithError(NullCallStatusErrorHandler, callback);
}

// IntegerType that matches Rust's `usize` / C's `size_t`
public class USize(value: Long = 0) : IntegerType(Native.SIZE_T_SIZE, value, true) {
    // This is needed to fill in the gaps of IntegerType's implementation of Number for Kotlin.
    override fun toByte() = toInt().toByte()
    // Needed until https://youtrack.jetbrains.com/issue/KT-47902 is fixed.
    @Deprecated("`toInt().toChar()` is deprecated")
    override fun toChar() = toInt().toChar()
    override fun toShort() = toInt().toShort()

    fun writeToBuffer(buf: ByteBuffer) {
        // Make sure we always write usize integers using native byte-order, since they may be
        // casted to pointer values
        buf.order(ByteOrder.nativeOrder())
        try {
            when (Native.SIZE_T_SIZE) {
                4 -> buf.putInt(toInt())
                8 -> buf.putLong(toLong())
                else -> throw RuntimeException("Invalid SIZE_T_SIZE: ${Native.SIZE_T_SIZE}")
            }
        } finally {
            buf.order(ByteOrder.BIG_ENDIAN)
        }
    }

    companion object {
        val size: Int
            get() = Native.SIZE_T_SIZE

        fun readFromBuffer(buf: ByteBuffer) : USize {
            // Make sure we always read usize integers using native byte-order, since they may be
            // casted from pointer values
            buf.order(ByteOrder.nativeOrder())
            try {
                return when (Native.SIZE_T_SIZE) {
                    4 -> USize(buf.getInt().toLong())
                    8 -> USize(buf.getLong())
                    else -> throw RuntimeException("Invalid SIZE_T_SIZE: ${Native.SIZE_T_SIZE}")
                }
            } finally {
                buf.order(ByteOrder.BIG_ENDIAN)
            }
        }
    }
}


// Map handles to objects
//
// This is used when the Rust code expects an opaque pointer to represent some foreign object.
// Normally we would pass a pointer to the object, but JNA doesn't support getting a pointer from an
// object reference , nor does it support leaking a reference to Rust.
//
// Instead, this class maps USize values to objects so that we can pass a pointer-sized type to
// Rust when it needs an opaque pointer.
//
// TODO: refactor callbacks to use this class
internal class UniFfiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<USize, T>()
    // Use AtomicInteger for our counter, since we may be on a 32-bit system.  4 billion possible
    // values seems like enough. If somehow we generate 4 billion handles, then this will wrap
    // around back to zero and we can assume the first handle generated will have been dropped by
    // then.
    private val counter = java.util.concurrent.atomic.AtomicInteger(0)

    val size: Int
        get() = map.size

    fun insert(obj: T): USize {
        val handle = USize(counter.getAndAdd(1).toLong())
        map.put(handle, obj)
        return handle
    }

    fun get(handle: USize): T? {
        return map.get(handle)
    }

    fun remove(handle: USize): T? {
        return map.remove(handle)
    }
}

// FFI type for Rust future continuations
internal interface UniFffiRustFutureContinuationCallbackType : com.sun.jna.Callback {
    fun callback(continuationHandle: USize, pollResult: Short);
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "uniffi_nym_transport"
}

private inline fun <reified Lib : Library> loadIndirect(
    componentName: String
): Lib {
    return Native.load<Lib>(findLibraryName(componentName), Lib::class.java)
}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

internal interface _UniFFILib : Library {
    companion object {
        internal val INSTANCE: _UniFFILib by lazy {
            loadIndirect<_UniFFILib>(componentName = "nym_transport")
            .also { lib: _UniFFILib ->
                uniffiCheckContractApiVersion(lib)
                uniffiCheckApiChecksums(lib)
                }
        }
    }

    fun uniffi_uniffi_nym_transport_fn_free_nymtransportclient(`ptr`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Unit
    fun uniffi_uniffi_nym_transport_fn_constructor_nymtransportclient_new(_uniffi_out_err: RustCallStatus, 
    ): Pointer
    fun uniffi_uniffi_nym_transport_fn_method_nymtransportclient_connect(`ptr`: Pointer,`gatewayUrl`: RustBuffer.ByValue,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_uniffi_nym_transport_fn_method_nymtransportclient_connect_rendezvous(`ptr`: Pointer,`pointId`: RustBuffer.ByValue,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_uniffi_nym_transport_fn_method_nymtransportclient_connect_with_custom_identity(`ptr`: Pointer,`rendezvousSeed`: RustBuffer.ByValue,`gatewayId`: RustBuffer.ByValue,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_uniffi_nym_transport_fn_method_nymtransportclient_cover_traffic_current_delay_ms(`ptr`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Long
    fun uniffi_uniffi_nym_transport_fn_method_nymtransportclient_cover_traffic_set_thermal_throttle(`ptr`: Pointer,`active`: Byte,_uniffi_out_err: RustCallStatus, 
    ): Unit
    fun uniffi_uniffi_nym_transport_fn_method_nymtransportclient_cover_traffic_start(`ptr`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Unit
    fun uniffi_uniffi_nym_transport_fn_method_nymtransportclient_cover_traffic_stop(`ptr`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Unit
    fun uniffi_uniffi_nym_transport_fn_method_nymtransportclient_disconnect(`ptr`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Unit
    fun uniffi_uniffi_nym_transport_fn_method_nymtransportclient_disconnect_all_rendezvous(`ptr`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Unit
    fun uniffi_uniffi_nym_transport_fn_method_nymtransportclient_disconnect_rendezvous(`ptr`: Pointer,`pointId`: RustBuffer.ByValue,_uniffi_out_err: RustCallStatus, 
    ): Unit
    fun uniffi_uniffi_nym_transport_fn_method_nymtransportclient_get_connection_info(`ptr`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_uniffi_nym_transport_fn_method_nymtransportclient_get_rendezvous_address(`ptr`: Pointer,`pointId`: RustBuffer.ByValue,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_uniffi_nym_transport_fn_method_nymtransportclient_is_connected(`ptr`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Byte
    fun uniffi_uniffi_nym_transport_fn_method_nymtransportclient_poll_rendezvous(`ptr`: Pointer,`pointId`: RustBuffer.ByValue,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_uniffi_nym_transport_fn_method_nymtransportclient_publish_at_rendezvous(`ptr`: Pointer,`pointId`: RustBuffer.ByValue,`myHandle`: RustBuffer.ByValue,`basePointId`: RustBuffer.ByValue,_uniffi_out_err: RustCallStatus, 
    ): Unit
    fun uniffi_uniffi_nym_transport_fn_method_nymtransportclient_receive_message(`ptr`: Pointer,`timeoutMs`: Long,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_uniffi_nym_transport_fn_method_nymtransportclient_send_message(`ptr`: Pointer,`handle`: RustBuffer.ByValue,`payload`: RustBuffer.ByValue,_uniffi_out_err: RustCallStatus, 
    ): Unit
    fun uniffi_uniffi_nym_transport_fn_method_nymtransportclient_tli_check_churn(`ptr`: Pointer,`signalType`: Byte,_uniffi_out_err: RustCallStatus, 
    ): Byte
    fun uniffi_uniffi_nym_transport_fn_method_nymtransportclient_tli_current_phase(`ptr`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Byte
    fun uniffi_uniffi_nym_transport_fn_method_nymtransportclient_tli_terminate_session(`ptr`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Unit
    fun uniffi_uniffi_nym_transport_fn_method_nymtransportclient_tli_transition(`ptr`: Pointer,`phase`: Byte,_uniffi_out_err: RustCallStatus, 
    ): Byte
    fun uniffi_uniffi_nym_transport_fn_func_session_decrypt_wrapper(`handle`: Long,`ciphertext`: RustBuffer.ByValue,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_uniffi_nym_transport_fn_func_session_destroy_wrapper(`handle`: Long,_uniffi_out_err: RustCallStatus, 
    ): Unit
    fun uniffi_uniffi_nym_transport_fn_func_session_encrypt_wrapper(`handle`: Long,`plaintext`: RustBuffer.ByValue,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_uniffi_nym_transport_fn_func_session_generate_confirmation_wrapper(`handle`: Long,`role`: Byte,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_uniffi_nym_transport_fn_func_session_get_obfs4_state_wrapper(`handle`: Long,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_uniffi_nym_transport_fn_func_session_verify_confirmation_wrapper(`handle`: Long,`confirmation`: RustBuffer.ByValue,`role`: Byte,_uniffi_out_err: RustCallStatus, 
    ): Byte
    fun uniffi_uniffi_nym_transport_fn_func_spake2_active_count_wrapper(_uniffi_out_err: RustCallStatus, 
    ): Long
    fun uniffi_uniffi_nym_transport_fn_func_spake2_cleanup_state_wrapper(`handleId`: Long,_uniffi_out_err: RustCallStatus, 
    ): Byte
    fun uniffi_uniffi_nym_transport_fn_func_spake2_finish_initiator_wrapper(`handleId`: Long,`inboundMsg`: RustBuffer.ByValue,_uniffi_out_err: RustCallStatus, 
    ): Long
    fun uniffi_uniffi_nym_transport_fn_func_spake2_start_initiator_wrapper(`password`: RustBuffer.ByValue,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_uniffi_nym_transport_fn_func_spake2_start_responder_wrapper(`password`: RustBuffer.ByValue,`inboundMsg`: RustBuffer.ByValue,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_uniffi_nym_transport_rustbuffer_alloc(`size`: Int,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_uniffi_nym_transport_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_uniffi_nym_transport_rustbuffer_free(`buf`: RustBuffer.ByValue,_uniffi_out_err: RustCallStatus, 
    ): Unit
    fun ffi_uniffi_nym_transport_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Int,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_uniffi_nym_transport_rust_future_continuation_callback_set(`callback`: UniFffiRustFutureContinuationCallbackType,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_poll_u8(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_cancel_u8(`handle`: Pointer,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_free_u8(`handle`: Pointer,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_complete_u8(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Byte
    fun ffi_uniffi_nym_transport_rust_future_poll_i8(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_cancel_i8(`handle`: Pointer,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_free_i8(`handle`: Pointer,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_complete_i8(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Byte
    fun ffi_uniffi_nym_transport_rust_future_poll_u16(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_cancel_u16(`handle`: Pointer,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_free_u16(`handle`: Pointer,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_complete_u16(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Short
    fun ffi_uniffi_nym_transport_rust_future_poll_i16(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_cancel_i16(`handle`: Pointer,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_free_i16(`handle`: Pointer,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_complete_i16(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Short
    fun ffi_uniffi_nym_transport_rust_future_poll_u32(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_cancel_u32(`handle`: Pointer,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_free_u32(`handle`: Pointer,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_complete_u32(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Int
    fun ffi_uniffi_nym_transport_rust_future_poll_i32(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_cancel_i32(`handle`: Pointer,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_free_i32(`handle`: Pointer,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_complete_i32(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Int
    fun ffi_uniffi_nym_transport_rust_future_poll_u64(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_cancel_u64(`handle`: Pointer,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_free_u64(`handle`: Pointer,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_complete_u64(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Long
    fun ffi_uniffi_nym_transport_rust_future_poll_i64(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_cancel_i64(`handle`: Pointer,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_free_i64(`handle`: Pointer,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_complete_i64(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Long
    fun ffi_uniffi_nym_transport_rust_future_poll_f32(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_cancel_f32(`handle`: Pointer,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_free_f32(`handle`: Pointer,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_complete_f32(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Float
    fun ffi_uniffi_nym_transport_rust_future_poll_f64(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_cancel_f64(`handle`: Pointer,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_free_f64(`handle`: Pointer,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_complete_f64(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Double
    fun ffi_uniffi_nym_transport_rust_future_poll_pointer(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_cancel_pointer(`handle`: Pointer,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_free_pointer(`handle`: Pointer,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_complete_pointer(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Pointer
    fun ffi_uniffi_nym_transport_rust_future_poll_rust_buffer(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_cancel_rust_buffer(`handle`: Pointer,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_free_rust_buffer(`handle`: Pointer,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_complete_rust_buffer(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_uniffi_nym_transport_rust_future_poll_void(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_cancel_void(`handle`: Pointer,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_free_void(`handle`: Pointer,
    ): Unit
    fun ffi_uniffi_nym_transport_rust_future_complete_void(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Unit
    fun uniffi_uniffi_nym_transport_checksum_func_session_decrypt_wrapper(
    ): Short
    fun uniffi_uniffi_nym_transport_checksum_func_session_destroy_wrapper(
    ): Short
    fun uniffi_uniffi_nym_transport_checksum_func_session_encrypt_wrapper(
    ): Short
    fun uniffi_uniffi_nym_transport_checksum_func_session_generate_confirmation_wrapper(
    ): Short
    fun uniffi_uniffi_nym_transport_checksum_func_session_get_obfs4_state_wrapper(
    ): Short
    fun uniffi_uniffi_nym_transport_checksum_func_session_verify_confirmation_wrapper(
    ): Short
    fun uniffi_uniffi_nym_transport_checksum_func_spake2_active_count_wrapper(
    ): Short
    fun uniffi_uniffi_nym_transport_checksum_func_spake2_cleanup_state_wrapper(
    ): Short
    fun uniffi_uniffi_nym_transport_checksum_func_spake2_finish_initiator_wrapper(
    ): Short
    fun uniffi_uniffi_nym_transport_checksum_func_spake2_start_initiator_wrapper(
    ): Short
    fun uniffi_uniffi_nym_transport_checksum_func_spake2_start_responder_wrapper(
    ): Short
    fun uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_connect(
    ): Short
    fun uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_connect_rendezvous(
    ): Short
    fun uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_connect_with_custom_identity(
    ): Short
    fun uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_cover_traffic_current_delay_ms(
    ): Short
    fun uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_cover_traffic_set_thermal_throttle(
    ): Short
    fun uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_cover_traffic_start(
    ): Short
    fun uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_cover_traffic_stop(
    ): Short
    fun uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_disconnect(
    ): Short
    fun uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_disconnect_all_rendezvous(
    ): Short
    fun uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_disconnect_rendezvous(
    ): Short
    fun uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_get_connection_info(
    ): Short
    fun uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_get_rendezvous_address(
    ): Short
    fun uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_is_connected(
    ): Short
    fun uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_poll_rendezvous(
    ): Short
    fun uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_publish_at_rendezvous(
    ): Short
    fun uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_receive_message(
    ): Short
    fun uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_send_message(
    ): Short
    fun uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_tli_check_churn(
    ): Short
    fun uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_tli_current_phase(
    ): Short
    fun uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_tli_terminate_session(
    ): Short
    fun uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_tli_transition(
    ): Short
    fun uniffi_uniffi_nym_transport_checksum_constructor_nymtransportclient_new(
    ): Short
    fun ffi_uniffi_nym_transport_uniffi_contract_version(
    ): Int
    
}

private fun uniffiCheckContractApiVersion(lib: _UniFFILib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 24
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_uniffi_nym_transport_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}

@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: _UniFFILib) {
    if (lib.uniffi_uniffi_nym_transport_checksum_func_session_decrypt_wrapper() != 47776.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_uniffi_nym_transport_checksum_func_session_destroy_wrapper() != 34447.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_uniffi_nym_transport_checksum_func_session_encrypt_wrapper() != 26061.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_uniffi_nym_transport_checksum_func_session_generate_confirmation_wrapper() != 10139.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_uniffi_nym_transport_checksum_func_session_get_obfs4_state_wrapper() != 46257.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_uniffi_nym_transport_checksum_func_session_verify_confirmation_wrapper() != 1354.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_uniffi_nym_transport_checksum_func_spake2_active_count_wrapper() != 32683.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_uniffi_nym_transport_checksum_func_spake2_cleanup_state_wrapper() != 13351.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_uniffi_nym_transport_checksum_func_spake2_finish_initiator_wrapper() != 42647.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_uniffi_nym_transport_checksum_func_spake2_start_initiator_wrapper() != 59432.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_uniffi_nym_transport_checksum_func_spake2_start_responder_wrapper() != 25414.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_connect() != 45052.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_connect_rendezvous() != 47100.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_connect_with_custom_identity() != 11788.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_cover_traffic_current_delay_ms() != 8540.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_cover_traffic_set_thermal_throttle() != 64454.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_cover_traffic_start() != 21367.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_cover_traffic_stop() != 15481.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_disconnect() != 44289.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_disconnect_all_rendezvous() != 55659.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_disconnect_rendezvous() != 36515.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_get_connection_info() != 19852.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_get_rendezvous_address() != 31249.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_is_connected() != 42808.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_poll_rendezvous() != 7260.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_publish_at_rendezvous() != 3637.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_receive_message() != 46455.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_send_message() != 23702.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_tli_check_churn() != 13540.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_tli_current_phase() != 56250.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_tli_terminate_session() != 24139.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_uniffi_nym_transport_checksum_method_nymtransportclient_tli_transition() != 59607.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_uniffi_nym_transport_checksum_constructor_nymtransportclient_new() != 45307.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// Async support

// Public interface members begin here.


public object FfiConverterUByte: FfiConverter<UByte, Byte> {
    override fun lift(value: Byte): UByte {
        return value.toUByte()
    }

    override fun read(buf: ByteBuffer): UByte {
        return lift(buf.get())
    }

    override fun lower(value: UByte): Byte {
        return value.toByte()
    }

    override fun allocationSize(value: UByte) = 1

    override fun write(value: UByte, buf: ByteBuffer) {
        buf.put(value.toByte())
    }
}

public object FfiConverterULong: FfiConverter<ULong, Long> {
    override fun lift(value: Long): ULong {
        return value.toULong()
    }

    override fun read(buf: ByteBuffer): ULong {
        return lift(buf.getLong())
    }

    override fun lower(value: ULong): Long {
        return value.toLong()
    }

    override fun allocationSize(value: ULong) = 8

    override fun write(value: ULong, buf: ByteBuffer) {
        buf.putLong(value.toLong())
    }
}

public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len)
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): Int {
        val sizeForLength = 4
        val sizeForString = value.length * 3
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            args.filterIsInstance<Disposable>()
                .forEach(Disposable::destroy)
        }
    }
}

inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

// The base class for all UniFFI Object types.
//
// This class provides core operations for working with the Rust `Arc<T>` pointer to
// the live Rust struct on the other side of the FFI.
//
// There's some subtlety here, because we have to be careful not to operate on a Rust
// struct after it has been dropped, and because we must expose a public API for freeing
// the Kotlin wrapper object in lieu of reliable finalizers. The core requirements are:
//
//   * Each `FFIObject` instance holds an opaque pointer to the underlying Rust struct.
//     Method calls need to read this pointer from the object's state and pass it in to
//     the Rust FFI.
//
//   * When an `FFIObject` is no longer needed, its pointer should be passed to a
//     special destructor function provided by the Rust FFI, which will drop the
//     underlying Rust struct.
//
//   * Given an `FFIObject` instance, calling code is expected to call the special
//     `destroy` method in order to free it after use, either by calling it explicitly
//     or by using a higher-level helper like the `use` method. Failing to do so will
//     leak the underlying Rust struct.
//
//   * We can't assume that calling code will do the right thing, and must be prepared
//     to handle Kotlin method calls executing concurrently with or even after a call to
//     `destroy`, and to handle multiple (possibly concurrent!) calls to `destroy`.
//
//   * We must never allow Rust code to operate on the underlying Rust struct after
//     the destructor has been called, and must never call the destructor more than once.
//     Doing so may trigger memory unsafety.
//
// If we try to implement this with mutual exclusion on access to the pointer, there is the
// possibility of a race between a method call and a concurrent call to `destroy`:
//
//    * Thread A starts a method call, reads the value of the pointer, but is interrupted
//      before it can pass the pointer over the FFI to Rust.
//    * Thread B calls `destroy` and frees the underlying Rust struct.
//    * Thread A resumes, passing the already-read pointer value to Rust and triggering
//      a use-after-free.
//
// One possible solution would be to use a `ReadWriteLock`, with each method call taking
// a read lock (and thus allowed to run concurrently) and the special `destroy` method
// taking a write lock (and thus blocking on live method calls). However, we aim not to
// generate methods with any hidden blocking semantics, and a `destroy` method that might
// block if called incorrectly seems to meet that bar.
//
// So, we achieve our goals by giving each `FFIObject` an associated `AtomicLong` counter to track
// the number of in-flight method calls, and an `AtomicBoolean` flag to indicate whether `destroy`
// has been called. These are updated according to the following rules:
//
//    * The initial value of the counter is 1, indicating a live object with no in-flight calls.
//      The initial value for the flag is false.
//
//    * At the start of each method call, we atomically check the counter.
//      If it is 0 then the underlying Rust struct has already been destroyed and the call is aborted.
//      If it is nonzero them we atomically increment it by 1 and proceed with the method call.
//
//    * At the end of each method call, we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
//    * When `destroy` is called, we atomically flip the flag from false to true.
//      If the flag was already true we silently fail.
//      Otherwise we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
// Astute readers may observe that this all sounds very similar to the way that Rust's `Arc<T>` works,
// and indeed it is, with the addition of a flag to guard against multiple calls to `destroy`.
//
// The overall effect is that the underlying Rust struct is destroyed only when `destroy` has been
// called *and* all in-flight method calls have completed, avoiding violating any of the expectations
// of the underlying Rust code.
//
// In the future we may be able to replace some of this with automatic finalization logic, such as using
// the new "Cleaner" functionaility in Java 9. The above scheme has been designed to work even if `destroy` is
// invoked by garbage-collection machinery rather than by calling code (which by the way, it's apparently also
// possible for the JVM to finalize an object while there is an in-flight call to one of its methods [1],
// so there would still be some complexity here).
//
// Sigh...all of this for want of a robust finalization mechanism.
//
// [1] https://stackoverflow.com/questions/24376768/can-java-finalize-an-object-when-it-is-still-in-scope/24380219
//
abstract class FFIObject(
    protected val pointer: Pointer
): Disposable, AutoCloseable {

    private val wasDestroyed = AtomicBoolean(false)
    private val callCounter = AtomicLong(1)

    open protected fun freeRustArcPtr() {
        // To be overridden in subclasses.
    }

    override fun destroy() {
        // Only allow a single call to this method.
        // TODO: maybe we should log a warning if called more than once?
        if (this.wasDestroyed.compareAndSet(false, true)) {
            // This decrement always matches the initial count of 1 given at creation time.
            if (this.callCounter.decrementAndGet() == 0L) {
                this.freeRustArcPtr()
            }
        }
    }

    @Synchronized
    override fun close() {
        this.destroy()
    }

    internal inline fun <R> callWithPointer(block: (ptr: Pointer) -> R): R {
        // Check and increment the call counter, to keep the object alive.
        // This needs a compare-and-set retry loop in case of concurrent updates.
        do {
            val c = this.callCounter.get()
            if (c == 0L) {
                throw IllegalStateException("${this.javaClass.simpleName} object has already been destroyed")
            }
            if (c == Long.MAX_VALUE) {
                throw IllegalStateException("${this.javaClass.simpleName} call counter would overflow")
            }
        } while (! this.callCounter.compareAndSet(c, c + 1L))
        // Now we can safely do the method call without the pointer being freed concurrently.
        try {
            return block(this.pointer)
        } finally {
            // This decrement always matches the increment we performed above.
            if (this.callCounter.decrementAndGet() == 0L) {
                this.freeRustArcPtr()
            }
        }
    }
}

public interface NymTransportClientInterface {
    @Throws(TransportException::class)
    fun `connect`(`gatewayUrl`: String): String@Throws(TransportException::class)
    fun `connectRendezvous`(`pointId`: String): String@Throws(TransportException::class)
    fun `connectWithCustomIdentity`(`rendezvousSeed`: List<UByte>, `gatewayId`: String): String
    fun `coverTrafficCurrentDelayMs`(): ULong
    fun `coverTrafficSetThermalThrottle`(`active`: Boolean)
    fun `coverTrafficStart`()
    fun `coverTrafficStop`()
    fun `disconnect`()
    fun `disconnectAllRendezvous`()@Throws(TransportException::class)
    fun `disconnectRendezvous`(`pointId`: String)
    fun `getConnectionInfo`(): ConnectionInfo@Throws(TransportException::class)
    fun `getRendezvousAddress`(`pointId`: String): String
    fun `isConnected`(): Boolean@Throws(TransportException::class)
    fun `pollRendezvous`(`pointId`: String): List<RendezvousMessage>@Throws(TransportException::class)
    fun `publishAtRendezvous`(`pointId`: String, `myHandle`: List<UByte>, `basePointId`: String)@Throws(TransportException::class)
    fun `receiveMessage`(`timeoutMs`: ULong): RendezvousMessage?@Throws(TransportException::class)
    fun `sendMessage`(`handle`: List<UByte>, `payload`: List<UByte>)
    fun `tliCheckChurn`(`signalType`: UByte): Boolean
    fun `tliCurrentPhase`(): UByte
    fun `tliTerminateSession`()@Throws(TransportException::class)
    fun `tliTransition`(`phase`: UByte): UByte
    companion object
}

class NymTransportClient(
    pointer: Pointer
) : FFIObject(pointer), NymTransportClientInterface {
    constructor() :
        this(
    rustCall() { _status ->
    _UniFFILib.INSTANCE.uniffi_uniffi_nym_transport_fn_constructor_nymtransportclient_new(_status)
})

    /**
     * Disconnect the object from the underlying Rust object.
     *
     * It can be called more than once, but once called, interacting with the object
     * causes an `IllegalStateException`.
     *
     * Clients **must** call this method once done with the object, or cause a memory leak.
     */
    override protected fun freeRustArcPtr() {
        rustCall() { status ->
            _UniFFILib.INSTANCE.uniffi_uniffi_nym_transport_fn_free_nymtransportclient(this.pointer, status)
        }
    }

    
    @Throws(TransportException::class)override fun `connect`(`gatewayUrl`: String): String =
        callWithPointer {
    rustCallWithError(TransportException) { _status ->
    _UniFFILib.INSTANCE.uniffi_uniffi_nym_transport_fn_method_nymtransportclient_connect(it,
        FfiConverterString.lower(`gatewayUrl`),
        _status)
}
        }.let {
            FfiConverterString.lift(it)
        }
    
    
    @Throws(TransportException::class)override fun `connectRendezvous`(`pointId`: String): String =
        callWithPointer {
    rustCallWithError(TransportException) { _status ->
    _UniFFILib.INSTANCE.uniffi_uniffi_nym_transport_fn_method_nymtransportclient_connect_rendezvous(it,
        FfiConverterString.lower(`pointId`),
        _status)
}
        }.let {
            FfiConverterString.lift(it)
        }
    
    
    @Throws(TransportException::class)override fun `connectWithCustomIdentity`(`rendezvousSeed`: List<UByte>, `gatewayId`: String): String =
        callWithPointer {
    rustCallWithError(TransportException) { _status ->
    _UniFFILib.INSTANCE.uniffi_uniffi_nym_transport_fn_method_nymtransportclient_connect_with_custom_identity(it,
        FfiConverterSequenceUByte.lower(`rendezvousSeed`),FfiConverterString.lower(`gatewayId`),
        _status)
}
        }.let {
            FfiConverterString.lift(it)
        }
    
    override fun `coverTrafficCurrentDelayMs`(): ULong =
        callWithPointer {
    rustCall() { _status ->
    _UniFFILib.INSTANCE.uniffi_uniffi_nym_transport_fn_method_nymtransportclient_cover_traffic_current_delay_ms(it,
        
        _status)
}
        }.let {
            FfiConverterULong.lift(it)
        }
    
    override fun `coverTrafficSetThermalThrottle`(`active`: Boolean) =
        callWithPointer {
    rustCall() { _status ->
    _UniFFILib.INSTANCE.uniffi_uniffi_nym_transport_fn_method_nymtransportclient_cover_traffic_set_thermal_throttle(it,
        FfiConverterBoolean.lower(`active`),
        _status)
}
        }
    
    
    override fun `coverTrafficStart`() =
        callWithPointer {
    rustCall() { _status ->
    _UniFFILib.INSTANCE.uniffi_uniffi_nym_transport_fn_method_nymtransportclient_cover_traffic_start(it,
        
        _status)
}
        }
    
    
    override fun `coverTrafficStop`() =
        callWithPointer {
    rustCall() { _status ->
    _UniFFILib.INSTANCE.uniffi_uniffi_nym_transport_fn_method_nymtransportclient_cover_traffic_stop(it,
        
        _status)
}
        }
    
    
    override fun `disconnect`() =
        callWithPointer {
    rustCall() { _status ->
    _UniFFILib.INSTANCE.uniffi_uniffi_nym_transport_fn_method_nymtransportclient_disconnect(it,
        
        _status)
}
        }
    
    
    override fun `disconnectAllRendezvous`() =
        callWithPointer {
    rustCall() { _status ->
    _UniFFILib.INSTANCE.uniffi_uniffi_nym_transport_fn_method_nymtransportclient_disconnect_all_rendezvous(it,
        
        _status)
}
        }
    
    
    
    @Throws(TransportException::class)override fun `disconnectRendezvous`(`pointId`: String) =
        callWithPointer {
    rustCallWithError(TransportException) { _status ->
    _UniFFILib.INSTANCE.uniffi_uniffi_nym_transport_fn_method_nymtransportclient_disconnect_rendezvous(it,
        FfiConverterString.lower(`pointId`),
        _status)
}
        }
    
    
    override fun `getConnectionInfo`(): ConnectionInfo =
        callWithPointer {
    rustCall() { _status ->
    _UniFFILib.INSTANCE.uniffi_uniffi_nym_transport_fn_method_nymtransportclient_get_connection_info(it,
        
        _status)
}
        }.let {
            FfiConverterTypeConnectionInfo.lift(it)
        }
    
    
    @Throws(TransportException::class)override fun `getRendezvousAddress`(`pointId`: String): String =
        callWithPointer {
    rustCallWithError(TransportException) { _status ->
    _UniFFILib.INSTANCE.uniffi_uniffi_nym_transport_fn_method_nymtransportclient_get_rendezvous_address(it,
        FfiConverterString.lower(`pointId`),
        _status)
}
        }.let {
            FfiConverterString.lift(it)
        }
    
    override fun `isConnected`(): Boolean =
        callWithPointer {
    rustCall() { _status ->
    _UniFFILib.INSTANCE.uniffi_uniffi_nym_transport_fn_method_nymtransportclient_is_connected(it,
        
        _status)
}
        }.let {
            FfiConverterBoolean.lift(it)
        }
    
    
    @Throws(TransportException::class)override fun `pollRendezvous`(`pointId`: String): List<RendezvousMessage> =
        callWithPointer {
    rustCallWithError(TransportException) { _status ->
    _UniFFILib.INSTANCE.uniffi_uniffi_nym_transport_fn_method_nymtransportclient_poll_rendezvous(it,
        FfiConverterString.lower(`pointId`),
        _status)
}
        }.let {
            FfiConverterSequenceTypeRendezvousMessage.lift(it)
        }
    
    
    @Throws(TransportException::class)override fun `publishAtRendezvous`(`pointId`: String, `myHandle`: List<UByte>, `basePointId`: String) =
        callWithPointer {
    rustCallWithError(TransportException) { _status ->
    _UniFFILib.INSTANCE.uniffi_uniffi_nym_transport_fn_method_nymtransportclient_publish_at_rendezvous(it,
        FfiConverterString.lower(`pointId`),FfiConverterSequenceUByte.lower(`myHandle`),FfiConverterString.lower(`basePointId`),
        _status)
}
        }
    
    
    
    @Throws(TransportException::class)override fun `receiveMessage`(`timeoutMs`: ULong): RendezvousMessage? =
        callWithPointer {
    rustCallWithError(TransportException) { _status ->
    _UniFFILib.INSTANCE.uniffi_uniffi_nym_transport_fn_method_nymtransportclient_receive_message(it,
        FfiConverterULong.lower(`timeoutMs`),
        _status)
}
        }.let {
            FfiConverterOptionalTypeRendezvousMessage.lift(it)
        }
    
    
    @Throws(TransportException::class)override fun `sendMessage`(`handle`: List<UByte>, `payload`: List<UByte>) =
        callWithPointer {
    rustCallWithError(TransportException) { _status ->
    _UniFFILib.INSTANCE.uniffi_uniffi_nym_transport_fn_method_nymtransportclient_send_message(it,
        FfiConverterSequenceUByte.lower(`handle`),FfiConverterSequenceUByte.lower(`payload`),
        _status)
}
        }
    
    
    override fun `tliCheckChurn`(`signalType`: UByte): Boolean =
        callWithPointer {
    rustCall() { _status ->
    _UniFFILib.INSTANCE.uniffi_uniffi_nym_transport_fn_method_nymtransportclient_tli_check_churn(it,
        FfiConverterUByte.lower(`signalType`),
        _status)
}
        }.let {
            FfiConverterBoolean.lift(it)
        }
    
    override fun `tliCurrentPhase`(): UByte =
        callWithPointer {
    rustCall() { _status ->
    _UniFFILib.INSTANCE.uniffi_uniffi_nym_transport_fn_method_nymtransportclient_tli_current_phase(it,
        
        _status)
}
        }.let {
            FfiConverterUByte.lift(it)
        }
    
    override fun `tliTerminateSession`() =
        callWithPointer {
    rustCall() { _status ->
    _UniFFILib.INSTANCE.uniffi_uniffi_nym_transport_fn_method_nymtransportclient_tli_terminate_session(it,
        
        _status)
}
        }
    
    
    
    @Throws(TransportException::class)override fun `tliTransition`(`phase`: UByte): UByte =
        callWithPointer {
    rustCallWithError(TransportException) { _status ->
    _UniFFILib.INSTANCE.uniffi_uniffi_nym_transport_fn_method_nymtransportclient_tli_transition(it,
        FfiConverterUByte.lower(`phase`),
        _status)
}
        }.let {
            FfiConverterUByte.lift(it)
        }
    
    

    
    companion object
    
}

public object FfiConverterTypeNymTransportClient: FfiConverter<NymTransportClient, Pointer> {
    override fun lower(value: NymTransportClient): Pointer = value.callWithPointer { it }

    override fun lift(value: Pointer): NymTransportClient {
        return NymTransportClient(value)
    }

    override fun read(buf: ByteBuffer): NymTransportClient {
        // The Rust code always writes pointers as 8 bytes, and will
        // fail to compile if they don't fit.
        return lift(Pointer(buf.getLong()))
    }

    override fun allocationSize(value: NymTransportClient) = 8

    override fun write(value: NymTransportClient, buf: ByteBuffer) {
        // The Rust code always expects pointers written as 8 bytes,
        // and will fail to compile if they don't fit.
        buf.putLong(Pointer.nativeValue(lower(value)))
    }
}




data class ConnectionInfo (
    var `myAddress`: String, 
    var `connected`: Boolean
) {
    
    companion object
}

public object FfiConverterTypeConnectionInfo: FfiConverterRustBuffer<ConnectionInfo> {
    override fun read(buf: ByteBuffer): ConnectionInfo {
        return ConnectionInfo(
            FfiConverterString.read(buf),
            FfiConverterBoolean.read(buf),
        )
    }

    override fun allocationSize(value: ConnectionInfo) = (
            FfiConverterString.allocationSize(value.`myAddress`) +
            FfiConverterBoolean.allocationSize(value.`connected`)
    )

    override fun write(value: ConnectionInfo, buf: ByteBuffer) {
            FfiConverterString.write(value.`myAddress`, buf)
            FfiConverterBoolean.write(value.`connected`, buf)
    }
}




data class RendezvousMessage (
    var `senderHandle`: List<UByte>, 
    var `payload`: List<UByte>
) {
    
    companion object
}

public object FfiConverterTypeRendezvousMessage: FfiConverterRustBuffer<RendezvousMessage> {
    override fun read(buf: ByteBuffer): RendezvousMessage {
        return RendezvousMessage(
            FfiConverterSequenceUByte.read(buf),
            FfiConverterSequenceUByte.read(buf),
        )
    }

    override fun allocationSize(value: RendezvousMessage) = (
            FfiConverterSequenceUByte.allocationSize(value.`senderHandle`) +
            FfiConverterSequenceUByte.allocationSize(value.`payload`)
    )

    override fun write(value: RendezvousMessage, buf: ByteBuffer) {
            FfiConverterSequenceUByte.write(value.`senderHandle`, buf)
            FfiConverterSequenceUByte.write(value.`payload`, buf)
    }
}




data class Spake2InitiatorHandle (
    var `handleId`: ULong, 
    var `outboundMsg`: List<UByte>
) {
    
    companion object
}

public object FfiConverterTypeSpake2InitiatorHandle: FfiConverterRustBuffer<Spake2InitiatorHandle> {
    override fun read(buf: ByteBuffer): Spake2InitiatorHandle {
        return Spake2InitiatorHandle(
            FfiConverterULong.read(buf),
            FfiConverterSequenceUByte.read(buf),
        )
    }

    override fun allocationSize(value: Spake2InitiatorHandle) = (
            FfiConverterULong.allocationSize(value.`handleId`) +
            FfiConverterSequenceUByte.allocationSize(value.`outboundMsg`)
    )

    override fun write(value: Spake2InitiatorHandle, buf: ByteBuffer) {
            FfiConverterULong.write(value.`handleId`, buf)
            FfiConverterSequenceUByte.write(value.`outboundMsg`, buf)
    }
}




data class Spake2ResponderResult (
    var `outboundMsg`: List<UByte>, 
    var `sessionHandle`: ULong
) {
    
    companion object
}

public object FfiConverterTypeSpake2ResponderResult: FfiConverterRustBuffer<Spake2ResponderResult> {
    override fun read(buf: ByteBuffer): Spake2ResponderResult {
        return Spake2ResponderResult(
            FfiConverterSequenceUByte.read(buf),
            FfiConverterULong.read(buf),
        )
    }

    override fun allocationSize(value: Spake2ResponderResult) = (
            FfiConverterSequenceUByte.allocationSize(value.`outboundMsg`) +
            FfiConverterULong.allocationSize(value.`sessionHandle`)
    )

    override fun write(value: Spake2ResponderResult, buf: ByteBuffer) {
            FfiConverterSequenceUByte.write(value.`outboundMsg`, buf)
            FfiConverterULong.write(value.`sessionHandle`, buf)
    }
}





sealed class SessionException(message: String): Exception(message) {
        // Each variant is a nested class
        // Flat enums carries a string error message, so no special implementation is necessary.
        class InvalidHandle(message: String) : SessionException(message)
        class EncryptionFailed(message: String) : SessionException(message)
        class DecryptionFailed(message: String) : SessionException(message)
        class InvalidRole(message: String) : SessionException(message)
        class SessionExpired(message: String) : SessionException(message)
        

    companion object ErrorHandler : CallStatusErrorHandler<SessionException> {
        override fun lift(error_buf: RustBuffer.ByValue): SessionException = FfiConverterTypeSessionError.lift(error_buf)
    }
}

public object FfiConverterTypeSessionError : FfiConverterRustBuffer<SessionException> {
    override fun read(buf: ByteBuffer): SessionException {
        
            return when(buf.getInt()) {
            1 -> SessionException.InvalidHandle(FfiConverterString.read(buf))
            2 -> SessionException.EncryptionFailed(FfiConverterString.read(buf))
            3 -> SessionException.DecryptionFailed(FfiConverterString.read(buf))
            4 -> SessionException.InvalidRole(FfiConverterString.read(buf))
            5 -> SessionException.SessionExpired(FfiConverterString.read(buf))
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
        
    }

    override fun allocationSize(value: SessionException): Int {
        return 4
    }

    override fun write(value: SessionException, buf: ByteBuffer) {
        when(value) {
            is SessionException.InvalidHandle -> {
                buf.putInt(1)
                Unit
            }
            is SessionException.EncryptionFailed -> {
                buf.putInt(2)
                Unit
            }
            is SessionException.DecryptionFailed -> {
                buf.putInt(3)
                Unit
            }
            is SessionException.InvalidRole -> {
                buf.putInt(4)
                Unit
            }
            is SessionException.SessionExpired -> {
                buf.putInt(5)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}





sealed class Spake2Exception(message: String): Exception(message) {
        // Each variant is a nested class
        // Flat enums carries a string error message, so no special implementation is necessary.
        class InvalidHandle(message: String) : Spake2Exception(message)
        class HandshakeFailed(message: String) : Spake2Exception(message)
        

    companion object ErrorHandler : CallStatusErrorHandler<Spake2Exception> {
        override fun lift(error_buf: RustBuffer.ByValue): Spake2Exception = FfiConverterTypeSpake2Error.lift(error_buf)
    }
}

public object FfiConverterTypeSpake2Error : FfiConverterRustBuffer<Spake2Exception> {
    override fun read(buf: ByteBuffer): Spake2Exception {
        
            return when(buf.getInt()) {
            1 -> Spake2Exception.InvalidHandle(FfiConverterString.read(buf))
            2 -> Spake2Exception.HandshakeFailed(FfiConverterString.read(buf))
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
        
    }

    override fun allocationSize(value: Spake2Exception): Int {
        return 4
    }

    override fun write(value: Spake2Exception, buf: ByteBuffer) {
        when(value) {
            is Spake2Exception.InvalidHandle -> {
                buf.putInt(1)
                Unit
            }
            is Spake2Exception.HandshakeFailed -> {
                buf.putInt(2)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}





sealed class TransportException(message: String): Exception(message) {
        // Each variant is a nested class
        // Flat enums carries a string error message, so no special implementation is necessary.
        class NotConnected(message: String) : TransportException(message)
        class ConnectionFailed(message: String) : TransportException(message)
        class SendFailed(message: String) : TransportException(message)
        class InvalidAddress(message: String) : TransportException(message)
        class RuntimeException(message: String) : TransportException(message)
        

    companion object ErrorHandler : CallStatusErrorHandler<TransportException> {
        override fun lift(error_buf: RustBuffer.ByValue): TransportException = FfiConverterTypeTransportError.lift(error_buf)
    }
}

public object FfiConverterTypeTransportError : FfiConverterRustBuffer<TransportException> {
    override fun read(buf: ByteBuffer): TransportException {
        
            return when(buf.getInt()) {
            1 -> TransportException.NotConnected(FfiConverterString.read(buf))
            2 -> TransportException.ConnectionFailed(FfiConverterString.read(buf))
            3 -> TransportException.SendFailed(FfiConverterString.read(buf))
            4 -> TransportException.InvalidAddress(FfiConverterString.read(buf))
            5 -> TransportException.RuntimeException(FfiConverterString.read(buf))
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
        
    }

    override fun allocationSize(value: TransportException): Int {
        return 4
    }

    override fun write(value: TransportException, buf: ByteBuffer) {
        when(value) {
            is TransportException.NotConnected -> {
                buf.putInt(1)
                Unit
            }
            is TransportException.ConnectionFailed -> {
                buf.putInt(2)
                Unit
            }
            is TransportException.SendFailed -> {
                buf.putInt(3)
                Unit
            }
            is TransportException.InvalidAddress -> {
                buf.putInt(4)
                Unit
            }
            is TransportException.RuntimeException -> {
                buf.putInt(5)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}




public object FfiConverterOptionalTypeRendezvousMessage: FfiConverterRustBuffer<RendezvousMessage?> {
    override fun read(buf: ByteBuffer): RendezvousMessage? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeRendezvousMessage.read(buf)
    }

    override fun allocationSize(value: RendezvousMessage?): Int {
        if (value == null) {
            return 1
        } else {
            return 1 + FfiConverterTypeRendezvousMessage.allocationSize(value)
        }
    }

    override fun write(value: RendezvousMessage?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeRendezvousMessage.write(value, buf)
        }
    }
}




public object FfiConverterSequenceUByte: FfiConverterRustBuffer<List<UByte>> {
    override fun read(buf: ByteBuffer): List<UByte> {
        val len = buf.getInt()
        return List<UByte>(len) {
            FfiConverterUByte.read(buf)
        }
    }

    override fun allocationSize(value: List<UByte>): Int {
        val sizeForLength = 4
        val sizeForItems = value.map { FfiConverterUByte.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<UByte>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.forEach {
            FfiConverterUByte.write(it, buf)
        }
    }
}




public object FfiConverterSequenceTypeRendezvousMessage: FfiConverterRustBuffer<List<RendezvousMessage>> {
    override fun read(buf: ByteBuffer): List<RendezvousMessage> {
        val len = buf.getInt()
        return List<RendezvousMessage>(len) {
            FfiConverterTypeRendezvousMessage.read(buf)
        }
    }

    override fun allocationSize(value: List<RendezvousMessage>): Int {
        val sizeForLength = 4
        val sizeForItems = value.map { FfiConverterTypeRendezvousMessage.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<RendezvousMessage>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.forEach {
            FfiConverterTypeRendezvousMessage.write(it, buf)
        }
    }
}
@Throws(SessionException::class)

fun `sessionDecryptWrapper`(`handle`: ULong, `ciphertext`: List<UByte>): List<UByte> {
    return FfiConverterSequenceUByte.lift(
    rustCallWithError(SessionException) { _status ->
    _UniFFILib.INSTANCE.uniffi_uniffi_nym_transport_fn_func_session_decrypt_wrapper(FfiConverterULong.lower(`handle`),FfiConverterSequenceUByte.lower(`ciphertext`),_status)
})
}


fun `sessionDestroyWrapper`(`handle`: ULong) =
    
    rustCall() { _status ->
    _UniFFILib.INSTANCE.uniffi_uniffi_nym_transport_fn_func_session_destroy_wrapper(FfiConverterULong.lower(`handle`),_status)
}


@Throws(SessionException::class)

fun `sessionEncryptWrapper`(`handle`: ULong, `plaintext`: List<UByte>): List<UByte> {
    return FfiConverterSequenceUByte.lift(
    rustCallWithError(SessionException) { _status ->
    _UniFFILib.INSTANCE.uniffi_uniffi_nym_transport_fn_func_session_encrypt_wrapper(FfiConverterULong.lower(`handle`),FfiConverterSequenceUByte.lower(`plaintext`),_status)
})
}

@Throws(SessionException::class)

fun `sessionGenerateConfirmationWrapper`(`handle`: ULong, `role`: UByte): List<UByte> {
    return FfiConverterSequenceUByte.lift(
    rustCallWithError(SessionException) { _status ->
    _UniFFILib.INSTANCE.uniffi_uniffi_nym_transport_fn_func_session_generate_confirmation_wrapper(FfiConverterULong.lower(`handle`),FfiConverterUByte.lower(`role`),_status)
})
}

@Throws(SessionException::class)

fun `sessionGetObfs4StateWrapper`(`handle`: ULong): List<UByte> {
    return FfiConverterSequenceUByte.lift(
    rustCallWithError(SessionException) { _status ->
    _UniFFILib.INSTANCE.uniffi_uniffi_nym_transport_fn_func_session_get_obfs4_state_wrapper(FfiConverterULong.lower(`handle`),_status)
})
}

@Throws(SessionException::class)

fun `sessionVerifyConfirmationWrapper`(`handle`: ULong, `confirmation`: List<UByte>, `role`: UByte): Boolean {
    return FfiConverterBoolean.lift(
    rustCallWithError(SessionException) { _status ->
    _UniFFILib.INSTANCE.uniffi_uniffi_nym_transport_fn_func_session_verify_confirmation_wrapper(FfiConverterULong.lower(`handle`),FfiConverterSequenceUByte.lower(`confirmation`),FfiConverterUByte.lower(`role`),_status)
})
}


fun `spake2ActiveCountWrapper`(): ULong {
    return FfiConverterULong.lift(
    rustCall() { _status ->
    _UniFFILib.INSTANCE.uniffi_uniffi_nym_transport_fn_func_spake2_active_count_wrapper(_status)
})
}


fun `spake2CleanupStateWrapper`(`handleId`: ULong): Boolean {
    return FfiConverterBoolean.lift(
    rustCall() { _status ->
    _UniFFILib.INSTANCE.uniffi_uniffi_nym_transport_fn_func_spake2_cleanup_state_wrapper(FfiConverterULong.lower(`handleId`),_status)
})
}

@Throws(Spake2Exception::class)

fun `spake2FinishInitiatorWrapper`(`handleId`: ULong, `inboundMsg`: List<UByte>): ULong {
    return FfiConverterULong.lift(
    rustCallWithError(Spake2Exception) { _status ->
    _UniFFILib.INSTANCE.uniffi_uniffi_nym_transport_fn_func_spake2_finish_initiator_wrapper(FfiConverterULong.lower(`handleId`),FfiConverterSequenceUByte.lower(`inboundMsg`),_status)
})
}

@Throws(Spake2Exception::class)

fun `spake2StartInitiatorWrapper`(`password`: List<UByte>): Spake2InitiatorHandle {
    return FfiConverterTypeSpake2InitiatorHandle.lift(
    rustCallWithError(Spake2Exception) { _status ->
    _UniFFILib.INSTANCE.uniffi_uniffi_nym_transport_fn_func_spake2_start_initiator_wrapper(FfiConverterSequenceUByte.lower(`password`),_status)
})
}

@Throws(Spake2Exception::class)

fun `spake2StartResponderWrapper`(`password`: List<UByte>, `inboundMsg`: List<UByte>): Spake2ResponderResult {
    return FfiConverterTypeSpake2ResponderResult.lift(
    rustCallWithError(Spake2Exception) { _status ->
    _UniFFILib.INSTANCE.uniffi_uniffi_nym_transport_fn_func_spake2_start_responder_wrapper(FfiConverterSequenceUByte.lower(`password`),FfiConverterSequenceUByte.lower(`inboundMsg`),_status)
})
}


