# i2pd config - ZeroChat

[sam]
enabled=true
port=7656

[http]
enabled=true
address=127.0.0.1
port=7070

[reseed]
urls=https://reseed.i2p-projekt.de/,https://reseed.memcpy.io/,https://reseed.onion.im/,https://i2p.novg.net/,https://reseed2.i2p.net/
