## Minimal i2pd.conf for ZeroChat

## General
daemon = false
service = true
log = stdout
loglevel = info

## Network
ipv4 = true
ipv6 = false
bandwidth = L
transit = false

[sam]
enabled = true
address = 127.0.0.1
port = 7656

[limits]
transittunnels = 0

